### ISSUE TITLE
Iterators are missing?

### ISSUE THREAD

**Issue by sebastian-philipp** [akrzemi1/Optional#29]
Hi,

As Optional is conceptually similar to a vector or list with at most one element, I'd purpose to implement iterators. One benefit would be the support for lots of ```<algorithm>``` functions. Another one would be code like this:
```
for(auto x: o) {
   foo(x);
}
```
This code would support out-of-the-box this optional type without any modification.

The theoretical background is that ```optional``` is a functor (the mathematical functor and not a C++ functor)  and a structure which can be traversed, like the Haskells ```Traversable``` or ```Foldable``` type class. Please have a look at this [Wiki page: Traversable and Foldable](https://wiki.haskell.org/Foldable_and_Traversable) for more infos.

As a fan of Haskell and C++, I'd love to be able to use some functional ideas in C++.

Thanks!

**Comment by akrzemi1** [comment]
This has already been proposed before, but I fail to see the practical benefit to the programmers. How is the code above better than:
```
if (o) {
   foo(*o);
}
```
What functions from `<algorithm>` would you like to use on `optional`? `find_if`? The argument that "it would make the language more like Haskell" are not working for me. I have to see that the addition is making the life easier for the C++ programmers. If you can convince me that the programs would be shorter, safer or more efficient, I would be willing to consider the change.

**Comment by sebastian-philipp** [comment]
I've started to use some small fragments of [my small project](https://github.com/sebastian-philipp/qt-continuation-monad) in my company and had to ```#if 0``` the ```boost::optional``` instances, because we don't use it at the moment. If Optional would have been a real container, it should be possible to support ```boost::optional``` without any dependency to it. 

Another example. Let's imagine a function ```optinonal<Tweet> downloadTweet(Url u);```. If ```downloadTweet``` fails, it returns an empty Optional. Now, let's use a map-reduce framework, because I'd like to download lots of tweets. That framework implements the reduce step by using something like this:

```
vector<R> v;
for(auto l: lists) {
    v.insert(v.end(), l.begin(), l.end());
}
```
Then, I could filter all successful downloads and join them together into the vector without waiting for the vendor to support Optional.

Of course, putting an Optional directly into a function from ```<algorithm>``` doesn't make much sense, but as a library writer, I can already support lots of container classes by using iterators. Adding support for Optional would require me to add extra code and I would bet that there is already a library somewhere that would support Optional out-of-the-box if it would support iterators.

Adding Iterators won't make code safer or more efficient, but it could increase the compatibility or lower the complexity of frameworks.

**Comment by akrzemi1** [comment]
> Then, I could filter all successful downloads and join them together into the vector without waiting for the vendor to support Optional.

Could you give me a somewhat bigger example, so that I could understand you better? What is `lists` in your example, and what is `R`?
