### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by rpavlik** [akrzemi1/Optional#30]
Wondering what the license on this code is. I've previously asked around, and a friend (@godbyk) asked STL, who asked Herb Sutter, regarding a `make_unique` implementation from the standard, and despite having written it they couldn't figure out the copyright or license terms.

**Comment by akrzemi1** [comment]
It is under [Boost Software License, Version 1.0](http://www.boost.org/LICENSE_1_0.txt). You can see it in the header file, and now I have added the notice also in the README file.
