### ISSUE TITLE
move operators

### ISSUE THREAD

**Issue by rodiers** [akrzemi1/Optional#32]
I'm probably abusing the issue system, but I had another question regarding to the design.

Why does the move constructor and move assignment operator leave the value of the moved-from object defined? Other classes in the standard library typically end up in a "default constructed" state.

If you'd say that it doesn't really matter since in general you shouldn't rely on the state of a moved object I would agree, but it is not really consistent with the rest of the standard library.

Thanks,
Bert

**Comment by akrzemi1** [comment]
I do not understand your question. Are you suggesting that the moved-from optional object should always be left in the state of not containing a value?

If so, the answer is: for performance. The way it is defined now, for a trivially copyable T, optional<T> is also trivially copyable and can be memcpy-ed. This would not be possible if the implementations were forced to change the state of the moved-from objects.

For a more detailed rationale, see the proposal: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3527.html#rationale.moved_from

**Comment by rodiers** [comment]
I see. 
You could have solved it in a different way by decoupling logical presence of a value and physical construction of the value by using two different booleans. One to specify that the object has been constructed and another one to specify that the value is present. This doesn't increase the size of the object since the booleans will be packed (but makes the bookkeeping slightly more complex).

Anyway, I'm nitpicking. It is a really nice library!
