### ISSUE TITLE
remove_reference => decay

### ISSUE THREAD

**Issue by rodiers** [akrzemi1/Optional#34]
According to the Library TS 
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4529.html#optional.object.assign
The assignment operator ```C++ template <class U> optional<T>& operator=(U&& v); ``` shall not participate in overload resolution unless  ```C++ is_same_v<decay_t<U>, T> ``` is true.

The current reference implementation however uses remove_reference and not decay:
```C++ 
 template <class U>
  auto operator=(U&& v)
  -> typename enable_if
  <
    is_same<typename remove_reference<U>::type, T>::value,
    optional&
  >::type
```

**Comment by akrzemi1** [comment]
Fixed
