### ISSUE TITLE
Make a partial specialization of `std::optional<T&>` which essentially implements as `T*`?

### ISSUE THREAD

**Issue by cbeck88** [akrzemi1/Optional#41]
Hi, thanks for publicizing this, I have been using a version of `optional` derived from this in a few projects and it has worked excellently for me.

One thing I wanted to suggest:  
I noticed that in your optional type, unlike in `boost::optional` (iirc), it is legal to take an optional over a reference type, e.g. `std::optional<T&>`. For various reasons I sometimes find this preferable to the more traditional but semantically very similar `T*` -- in particular, `optional` indicates clearly to the programmer that the value might be vacant and that they should expect this, also, occasionally I write code that treats any `optional<T>` type a certain way. For instance a template function which takes a series of types, might assume that an `optional<T>` indicates that an error encountered while obtaining a value in some context should not be fatal, while in other cases that error should be logged / propagated etc.

However, a drawback is that `std::optional<T&>` may take up more space than a `T*`, since it requires a bool. If the memory must be aligned then it may double the space I suppose.

A natural idea then is that in case that the template parameter is a reference type, the `std::optional` template class should select a different `optional_base` type which uses `T*` to represent the value, and `nullptr` to represent vacancy. Since nothing can be legally placed at the null address anyways...

I am thinking to tweak the version used in one of my projects in this manner, but I would like to hear what you think about it / if you anticipate any problems.

Thanks also for writing your blog, by the way.

**Comment by cbeck88** [comment]
I noticed that in the recent version, but not in the version in my project, you actually have already done this. Thanks and sorry to bother you. :smile:

**Comment by akrzemi1** [comment]
I happen to maintain two similar libraries: one is `boost::optional` from Boost, the other is my reference implementation of `optional` from [Fundamentals Technical Specification](https://github.com/cplusplus/fundamentals-ts) (call it `std::experimental::optional`).

This GitHub project is about `std::experimental::optional`. Your remark is about `boost::optional`. Indeed, I plan to add a specialization for `boost::optional<T&>` in the next Boost release: 1.61. Currently,the change is only available in develop branch.
