### ISSUE TITLE
T::T(T&&) and T::operator=(T&&) are invoked directly by optional<T>, add to standard?

### ISSUE THREAD

**Issue by tamaskenez** [akrzemi1/Optional#42]
Say, we have a class whose invariant is to be always valid:

    class File {
    public:
        File() = delete;
        File(const char* filename, const char* mode); // throws on error
        [ copy/move ctors and assignments deleted ]
    };

Note, that move constructor and assignment are deleted since a moved-out object would have to be invalid.

In case we need an object that is either or valid File or not, we can use `optional<File>`.

In case we need a movable `optional<File>` we do need to provide the deleted move constructor and assignment. If we add those as private methods and provide friend access to `optional<File>` the invariant of the plain File remains intact:
  
    class File {
    public:
        ...
    private:
        friend class optional<File>;
        File(File&& x) {...}
        File& operator=(File&& x) {...}
    };

This solution happens to work with your implementation of `optional` because these methods happen to be invoked by `optional<>` itself. If they were invoked by some intermediate helper class it would not work since the helper class should be specified as friend.

What do you think, is this a valid use case? If so, should this requirement of direct invocation of move constructors and assignments be added to the standard?

**Comment by akrzemi1** [comment]
Frankly, it was never a design goal for `std::optional` or `boost::optional` to work this way. I am in fact surprised that you have found this implementation to work, because I am pretty sure it forwards calls to helper classes.

Also, If you move from an optional object that contains a value, it still contains a value after move. Are you OK with this?

**Comment by tamaskenez** [comment]
I know it was only a matter of luck but this implementation does call both methods directly:

- T's move constructor is called by [`optional::initialize()`, line #384](https://github.com/akrzemi1/Optional/blob/master/optional.hpp#L384)
- T's move assignment is called by [`optional::operator=()`, line #456](https://github.com/akrzemi1/Optional/blob/master/optional.hpp#L456)

> Also, If you move from an optional object that contains a value, it still contains a value after move. Are you OK with this?

Good point, that's not OK. I expect a moved-out optional to be disengaged. I've just read [N3672/rationale.moved_from](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3672.html#rationale.moved_from) and I'm trying to understand the two performance reasons listed there.

Since the moved-from behaviour prevents my design in the first place, I'm closing this issue.

Thanks for your time,
Tamas

**Comment by akrzemi1** [comment]
I wonder if [this alternate library](https://github.com/akrzemi1/markable) does not address your issue. It has a section on types with strong invariants: https://github.com/akrzemi1/markable/blob/master/documentation/overview.md#using-pod-storage-for-empty-value

**Comment by tamaskenez** [comment]
Thanks, I checked out `markable` and it's a very nice idea and library. I think it's purpose is somewhat different from what I need here (referring to your [blog article](https://akrzemi1.wordpress.com/2015/07/15/efficient-optional-values) I have something like motivation 1. while markable is for 3.). But what it's made for it's great.

**Comment by akrzemi1** [comment]
Well, the library evolved a bit since I have written this blog post. There is a way to indicate the empty value in a bit-pattern that does not necessarily constitute a valid value. It looks to me like your use case. I will try to experiment with it when I have some time.

**Comment by tamaskenez** [comment]
I've also read the documentation. You're right, my use case can be solved with `markable` but not with `markable_pod_storage_type` but simply with `markable_type`. It's because that my `class File` can hold a null state internally, it's just that this capability is not exposed (no public default ctor, copy/move). That's why the user can be sure wherever `File` is written, it is a valid File.

So this would work:

    struct mark_File : markable_type<File> {
        static storage_type marked_value() { 
            return {}; // private default ctor
        }
        static bool is_marked_value(const storage_type& v) {
            return v.is_null(); // also private
        }
    };

But I feel `optional<T>` would be a better fit, because:
- I don't need to spare a bool
- It's better to have less boilerplate (`mark_File`)
- it's better to have a simple, more obvious type for the optional (`optional<File>` vs `markable<mark_File>`)
- have the same problem that File should specify `markable<mark_File>` or maybe a helper class as friend to allow using its private move-ctor.
