### ISSUE TITLE
critique of arguments for n3672/rationale.moved_from

### ISSUE THREAD

**Issue by tamaskenez** [akrzemi1/Optional#43]
The [n3672 / rationale.moved_from](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3672.html#rationale.moved_from) lists two performance reasons for backing the decision that the moved-from optional is not disengaged.

Traditionally C++ developers used to incorporate optionality into most types: nullable pointers, default-constructible resource types are still the norm.
 
The optional type could be used to build stricter and safer types by providing easy switching between the always-valid and maybe-valid versions of the same type. 

Since the decision above may prevent using the optional type in those, important use cases I'd like to discuss the arguments that lead to this decision.

1. The first argument is effectively stating that moving from and into an `optional<T>` where `T` *doesn't have efficient move* could be more efficient by saving a destruction and a (move-)construction.
2. The second argument is that if T is trivially-copyable, then moving `optional<T>` can be reduced to a `memcpy` if the right-hand side of the move operation need not to be updated (destructed, disengaged).

I don't think either of these arguments should be given too much weight, because:

- moving a type that doesn't have efficient move (first argument) is inefficient to move in the first place. The cost of the move is expected to be far more costly then the destruction or move-construction.
- storing significant amount of data on the stack is not realistic. And once we're using the heap, moving is an O(1) operation. Compare this to the minor performance gain a trivial-copy can bring.
- when writing performance-critical code one would never store data in an array of `optional<int>`'s (it would be probably `array<int>` + bitarray)

It's true that the standard allows the right-hand side of the move-assignment left in an unspecified state but it's just because an unspecified T type has unspecified semantics. The move semantics of a concrete type should follow from the semantics of the type. All movable types in the std namespace satisfy this and all do something with the rhs of the move, in particular the ["least-surprising"](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) thing. `optional` is a concrete type with specified semantics and even N3672 acknowledges that disengaging-after-move would be the least surprising thing to do:

> The fact that the moved-from optional is not disengaged may look 'uncomfortable' at first, ...

**Comment by akrzemi1** [comment]
Tamas, may I suggest that you raise this issue at [isocpp.org forum](https://groups.google.com/a/isocpp.org/forum/?fromgroups#!forum/std-proposals). On this GitHub repository you are only discussing with one person, who is naturally biased towards his solution.

**Comment by tamaskenez** [comment]
Thanks, I think the forum is a good idea, I'll study the discussion there and may post my thoughts.

It just came to my mind that a policy could be added (specified like `iterator_category`) to control what should be done with the moved-from optional. The default would be the the current leave-as-it-is, the alternative would be the disangage_after_move_policy.

Anyway, first I need to find it out on the forum what others think of my motivating use case at all.

**Comment by tamaskenez** [comment]
Well, I've changed my mind.

I've just read a few bits on how certain things go in the Rust language. Now I think that what I miss is not that a moved-from optional should be disengaged but that the compiler should not allow any operations on any moved-from values, except dtor or assignments (I know this is not enforceable).

Since querying the engagement status of a moved-from optional is (should be) theoretically illegal there's no end in updating it after the move. I think this is a better rationale for [rationale.moved_from](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3672.html#rationale.moved_from)

Thanks for your time and sorry for dragging you into this.
