### ISSUE TITLE
Future proof #include

### ISSUE THREAD

**Issue by adishavit** [akrzemi1/Optional#48]
What is the best way to include `akrzemi1/Optional` in such a way that it is future proof and if/when the compiler has `std::optional` support _that_ version will be used?

Can the `#include` be completely bypassed (using macros) or does the implementation simply fall back on the `std` one if it exists?

**Comment by akrzemi1** [comment]
This library does not have such option. (It was meant only to prove that Optional is implementable.) The best option, I guess, is to include `<experimental/optional>` instead of this library.
