### ISSUE TITLE
Support for sentinel values

### ISSUE THREAD

**Issue by bjoernpollex** [akrzemi1/Optional#49]
Has the idea of supporting specializations for sentinel values ever been discussed? The only mention of it I could find was on [r/cpp][1], so I'm not sure if it just hasn't been discussed, or if it has, but was rejected. If it is the former, would you be open to consider such a feature?

[1]: https://www.reddit.com/r/cpp/comments/3aqm1q/why_is_boostoptionalstdoptional_so_space/csg1ag6

**Comment by akrzemi1** [comment]
It has. For some discussion, see here: https://groups.google.com/a/isocpp.org/forum/#!topic/std-proposals/46J1onhWJ-s/discussion
I believe it did not obtain a consensus. For a practical implementation of sentinel value wrappers see this library: https://github.com/akrzemi1/markable
As to making it a specialization of std::optional, it was concluded that explicit specialization is no better than a different type. As you will be able to see from the implementation of `markable` (in the other link), the interface of std::optional is incompatible with some requirements of sentinel value wrapper. In particular, std::optional must guarantee that:

```c++
template <typename T>
void expectation(std::optional<T> o, T some_T)
{
  if (o)          // for any 'initialized' optional
  {
    *o = some_T;  // modifying the contained value
    assert (o);   // must not un-initialize the optional
  }
}
```

**Comment by bjoernpollex** [comment]
Great, thanks for the response. Sad to hear, it would have been great to have a uniform interface for both the use-cases.
