### ISSUE TITLE
Compilation fails with CUDA 8.0 nvcc and GCC 6.2.1

### ISSUE THREAD

**Issue by eyalroz** [akrzemi1/Optional#50]
I've been happily using this class with CUDA 7.5/8.0 and GCC 4.9.3 for a while. Now I'm trying to upgrade to GCC 6.2.1, and I'm getting compilation errors. They do not occur when just compiling with GCC 6.2.1 directly - only when compiling via nvcc. See my [Stackoverflow question](http://stackoverflow.com/q/39832361/1593077) on this matter.

A minimum working (or rather breaking) example:

Code:

```#include` "optional.hpp"
int main() { return 0; }```

Compilation command:

```nvcc -std=c++11 -Xcompiler -D__CORRECT_ISO_CPP11_MATH_H_PROTO -Wno-deprecated-gpu-targets -o a a.cu```

**Comment by akrzemi1** [comment]
From SO question, I gather it is not related to Optional.
