### ISSUE TITLE
How to set an optional

### ISSUE THREAD

**Issue by SuicSoft** [akrzemi1/Optional#51]
I am trying to migrate a project using boost to C++11 and I am using this . But I am getting this error 

```
error: no match for ‘operator=’ (operand types are ‘std::experimental::optional<std::__cxx11::basic_string<char> >’ and ‘char*’)
```

When I simply set my `optional<T>`  using  `datadir = argv[++i];`.

How can I set a `optional<T>`

**Comment by akrzemi1** [comment]
This implementation does not offer a "mixed" assignment from `U` to `optional<T>`. You have two options:

Option 1: convert to `std::string` before the assignment
```c++
datadir = std::string{argv[++i]};
```
Option 2: use `emplace` instead
```c++
datadir.emplace(argv[++i]);
```

The second one is faster but offers weaker exception-safety guarantee.

**Comment by SuicSoft** [comment]
@akrzemi1 Thanks :)
