### ISSUE TITLE
Add a has_value() method

### ISSUE THREAD

**Issue by eyalroz** [akrzemi1/Optional#52]
C++14's std::experimental::optional was missing the useful (public) method `has_value()`, which is essentially an exposure of (the private) `initialized()` method. Shouldn't this optional implementation also have it?

**Comment by akrzemi1** [comment]
Added.

(Thanks for the interest in this implementation. Originally, I only wanted it to be a prove of implementability.)

**Comment by eyalroz** [comment]
It's quite useful for people who are stuck with C++11 or earlier due to objective constraints, e.g. using CUDA or writing code that needs to interact with it. Although, frankly, I'm trying to somehow clear out the use of your code from my own CUDA code and try to keep optional's in host-side code so I can switch it to C++14's implementation.
