### ISSUE TITLE
Why not to put clear() to the public scope?

### ISSUE THREAD

**Issue by daotrungkien** [akrzemi1/Optional#53]
It seems that currently there is no way to make the object null again after having a value. I think it makes sense to have clear() in public scope, or to have copy assignments to nullable objects.

**Comment by akrzemi1** [comment]
```c++
optional<int> oi {1}; // optional contains a value
oi = nullopt;         // optional no longer contains a value
```
So, there is a way to make the object "null" again. Or did I misunderstand your concern?

**Comment by daotrungkien** [comment]
That's exactly what I looked for. Sorry for my quick wrong conclusion, after trying the following assignment with no luck:
`oi = optional<int>();`
Thanks for your contribution by the way.

**Comment by akrzemi1** [comment]
The way you describe should also work. See:
http://melpon.org/wandbox/permlink/Nh3jVEGhtv1BMKX8

Although now we require move assignment to be called.

**Comment by daotrungkien** [comment]
Sorry, may be I made something else wrong last time.

**Comment by akrzemi1** [comment]
I will close this issue then. For completeness' sake, let me mention that there is another C++11 syntax for resetting the optional:

```c++
oi = {};
```

But this one also requires a move. Thus, the most efficient, recommended way of resetting the optional is:

```c++
oi = nullopt; 
```

**Comment by rodiers** [comment]
The C++ standard added reset for this: http://en.cppreference.com/w/cpp/utility/optional/reset
You don't plan to remain in-sync with the standard?

**Comment by akrzemi1** [comment]
I'll add one, when I find some time to unit-test it.

**Comment by akrzemi1** [comment]
Now it is there.
