### ISSUE TITLE
Issue with std::partition

### ISSUE THREAD

**Issue by arnaudbrejeon** [akrzemi1/Optional#56]
On OSX, Xcode9.3, the following code fails to build:

```
#include <algorithm>
#include <vector>

#include "optional.hpp"
namespace tr2 = std::experimental;

int main(int argc, const char* argv[]) {
    auto vec = std::vector<tr2::optional<int>>{};
    std::partition(begin(vec), end(vec), [](const auto& val) { return val; });
    return 0;
}
```

Errors:
optional.hpp:489:102: Exception specification of 'swap' uses itself
optional.hpp:489:122: Too many arguments to function call, expected single argument 'rhs', have 2 arguments

**Comment by akrzemi1** [comment]
Can you tell me something about this compiler? What support of C++14 does it offer? E.g., does it have `std::__is_nothrow_swappable` or similar? Is the compiler testable online?

**Comment by arnaudbrejeon** [comment]
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang --version
Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

CompileC ./Intermediates.noindex/testPerf.build/Release/testPerf.build/Objects-normal/x86_64/main.o testPerf/main.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 **-std=gnu++14 -stdlib=libc++** -fmodules -gmodules -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -Os -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wdocumentation -Wunreachable-code -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -mmacosx-version-min=10.13 -g -fvisibility=hidden -fvisibility-inlines-hidden -Wno-sign-conversion -Winfinite-recursion -Wmove -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wrange-loop-analysis -Wunguarded-availability

**Comment by arnaudbrejeon** [comment]
I have fixed it locally by changing
            void swap(optional<T>& rhs) noexcept(is_nothrow_move_constructible<T>::value && noexcept(swap(declval<T&>(), declval<T&>())))
to
            void swap(optional<T>& rhs) noexcept(is_nothrow_move_constructible<T>::value && noexcept( **std::** swap(declval<T&>(), declval<T&>())))

But I'm not sure it is the best fix

**Comment by viboes** [comment]
```
noexcept(swap(declval<T&>(), declval<T&>())))
```

is clearly not correct, but using `std::swap` is not more correct.

@akrzemi1 you need to define a `adl_swap` function that you can use in a `noexcept` expression, or use `is_nothrow_swappable`

```c++
noexcept(adl_swap::swap(declval<T&>(), declval<T&>())))
```

where

```c++
namesapce adl_swap {
    void swap(T& t, T& u) {
        using std::swap;
        swap(t,u);
    }
}
```

**Comment by akrzemi1** [comment]
The `adl_swap` will not work: I would have to provide `noexcept()` specification and I would arrive at the same problem (recursively). As you say, I would have to us std::is_nothrow_swappable` or GCC's `std::__is_nothrow_swappable` but I do not know how to reliably detect it on MacOSX.

@arnaudbrejeon: I would need your help. Could you check if on your implementation of the standard library, you have wither of the two traits?

**Comment by arnaudbrejeon** [comment]
I tried the different compiler options available in XCode9.3:

```
                 std::is_nothrow_swappable   std::__is_nothrow_swappable
-std=gnu++11     Fails                       OK
-std=c++11       Fails                       OK
-std=gnu++14     Fails                       OK
-std=c++14       Fails                       OK
-std=gnu++17     OK                          OK
-std=c++17       OK                          OK
```

**Comment by akrzemi1** [comment]
So this is basically clang, yes? Can you observe macro `__clang__` being defined while compiling?

**Comment by arnaudbrejeon** [comment]
Yes, it's clang and __clang__ is defined

**Comment by viboes** [comment]
@akrzemi1 Oh, you are right. 

What about 
https://wandbox.org/permlink/7h4z1sXUPw6ZqmFf
?

**Comment by akrzemi1** [comment]
Clever!

**Comment by akrzemi1** [comment]
Thanks Vicente! and thanks Arnaud for reporting this. Vicente's fix should make the test case compile.
