### ISSUE TITLE
Please add .gitattributes

### ISSUE THREAD

**Issue by ned14** [akrzemi1/Optional#64]
As reported at https://github.com/ned14/quickcpplib/issues/12, the need to poke a .gitattributes into submodule Optional is problematic for some.

A suitable .gitattributes can be found at https://github.com/ned14/quickcpplib/blob/master/.gitattributes.

**Comment by ned14** [comment]
Any update on this?

**Comment by akrzemi1** [comment]
Sorry, I somehow missed this.
I am not too well familiar with all the tricks in git. How is this supposed to work. Do I just put the linked file in the root of my repository?

**Comment by ned14** [comment]
No problem, I raised the issue in the middle of the Boost release cycle in any case. We were all busy.

Strictly speaking, you ought to add the `.gitattributes`, and then follow the CRLF normalisation instructions from https://docs.github.com/en/github/using-git/configuring-git-to-handle-line-endings#refreshing-a-repository-after-changing-line-endings. However, assuming that you have never committed anything from Windows, the refresh step ought to be a no-op.

Once done, git checkouts on Windows will have CRLF, on POSIX they'll be LF, and everything will "just work" in terms of git submodules not showing dirty all the time on Windows. Thanks Andrzej.

**Comment by akrzemi1** [comment]
Does this commit address your request?
https://github.com/akrzemi1/Optional/commit/2b43315458a99fc5de1da6e7bc0ddd364b26d643

**Comment by ned14** [comment]
Looks good. Thanks!
